version: 2.1
jobs:
    run_tests:
          docker:
              - image: circleci/python:3.8.2
          steps:
              - checkout
              - run:
                    name: install python dependencies
                    command: |
                        pip install --user -r requirements.txt
              - run:
                  name: run unit tests
                  command: |
                        pytest -v --cov
                        tox -e lint
              - store_test_results:
                  path: /bin/test_reports
              - store_artifacts:
                  path: /bin/final_build
workflows:
  build_test:
      jobs:
          - run_tests
