version: 2.1
jobs:
    run_tests:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run:
                name: Install Python Dependencies
                command: |
                    pip install --user -r requirements.txt
            - run:
                name: Run Unit Tests
                command: |
                    tox -e lint
            - store_test_results:
                path: /bin/test_reports
            - store_artifacts:
                  path: /bin/final_build

workflows:
    build_test:
        jobs:
            - run_tests
